# Generated by Django 2.1.3 on 2019-03-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmsdocinfo',
            name='examine_status',
            field=models.IntegerField(default=0, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='kmsdocinfo',
            name='release_status',
            field=models.IntegerField(default=0, verbose_name='发布状态'),
        ),
    ]
