# Generated by Django 2.1.3 on 2019-02-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KmsFilePath',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(max_length=64)),
                ('path', models.CharField(max_length=128)),
                ('doc_info', models.ForeignKey(on_delete='id', to='kms_app.KmsDocInfo')),
            ],
        ),
    ]
