# Generated by Django 2.1.3 on 2019-03-08 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kms_app', '0003_remove_kmsdocinfo_issuer_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kmsdocinfo',
            name='examine_status',
        ),
        migrations.RemoveField(
            model_name='kmsdocinfo',
            name='release_status',
        ),
    ]
