# Generated by Django 2.1.3 on 2019-02-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms_app', '0003_auto_20190226_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmsfilepath',
            name='name',
            field=models.CharField(default=1, max_length=128),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='kmsfilepath',
            name='path',
            field=models.CharField(max_length=256),
        ),
    ]
