# Generated by Django 2.1.3 on 2019-03-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms_app', '0004_auto_20190228_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='KmsHomePageSettings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=16, verbose_name='导航名称')),
                ('view_permissions', models.CharField(max_length=8, verbose_name='查看权限')),
                ('filter_conditions', models.CharField(max_length=32, verbose_name='过滤条件')),
            ],
        ),
    ]
