# Generated by Django 2.1.3 on 2019-03-01 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kms_app', '0005_kmshomepagesettings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kmshomepagesettings',
            old_name='name',
            new_name='nav_name',
        ),
    ]
