# Generated by Django 2.1.3 on 2019-03-08 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms_app', '0005_kmsdocinfo_issuer_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmsdocinfo',
            name='issuer_account',
            field=models.CharField(db_index=True, default=None, max_length=16, verbose_name='用户名'),
        ),
    ]
