# Generated by Django 2.1.3 on 2019-03-01 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms_app', '0006_auto_20190301_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmshomepagesettings',
            name='view_permissions',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='查看权限'),
        ),
    ]
