# Generated by Django 2.1.3 on 2019-03-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms_app', '0006_auto_20190308_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmsdocinfo',
            name='auditor_issuer_account',
            field=models.CharField(default=None, max_length=16, verbose_name='审核人账户'),
        ),
        migrations.AlterField(
            model_name='kmsdocinfo',
            name='issuer_account',
            field=models.CharField(db_index=True, default=None, max_length=16, verbose_name='发布人账户'),
        ),
    ]
