# Generated by Django 2.1.3 on 2019-03-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms_app', '0007_auto_20190301_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmshomepagesettings',
            name='view_permissions',
            field=models.ForeignKey(blank=True, null=True, on_delete='id', to='kms_app.KmsUserPermissions', verbose_name='查看权限'),
        ),
    ]
