# Generated by Django 2.1.3 on 2019-03-08 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kms_app', '0008_auto_20190308_1624'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='kmsdocinfo',
            index_together={('title', 'issuer', 'classify_name')},
        ),
    ]
