# Generated by Django 2.1.3 on 2019-03-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms_app', '0008_auto_20190301_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kmshomepagesettings',
            name='filter_conditions',
            field=models.CharField(max_length=64, verbose_name='过滤条件'),
        ),
    ]
