# Generated by Django 2.1.3 on 2019-03-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kms_app', '0009_auto_20190308_1715'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='kmsdocinfo',
            index_together={('del_status', 'doc_status'), ('title', 'issuer', 'classify_name')},
        ),
    ]
