# Generated by Django 2.1.7 on 2019-03-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms_app', '0010_auto_20190308_1716'),
    ]

    operations = [
        migrations.AddField(
            model_name='kmsdocinfo',
            name='subject',
            field=models.CharField(db_index=True, default=None, max_length=32, verbose_name='主题词'),
        ),
        migrations.AlterField(
            model_name='kmsdocinfo',
            name='auditor',
            field=models.CharField(db_index=True, default=None, max_length=16, verbose_name='审核人'),
        ),
    ]
